import AuthFrom from "@/components/AuthFrom/AuthFrom";
import styled from "@emotion/styled";
import Head from "next/head";

const Register = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <OverrideMain>
        <AuthFrom isRegister={true} />
      </OverrideMain>
    </>
  );
};

export default Register;

const OverrideMain = styled.main`
  top: 0;

  @media only screen and (max-width: 56.25rem) {
    z-index: 100;
    width: 100vw;
    height: 100vh;
  }
`;
